# Generated by Django 3.2.13 on 2023-03-08 07:31

import chat.models.chat
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0006_coach_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('file', models.ImageField(blank=True, null=True, upload_to=chat.models.chat.session_image_directory_path)),
                ('timestamp', models.DateTimeField()),
                ('type', models.CharField(choices=[('text', 'TEXT'), ('file', 'FILE')], default='text', max_length=100, verbose_name='Type of Message')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='academy.session')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sessions Chat History',
                'ordering': ('timestamp',),
            },
        ),
        migrations.CreateModel(
            name='CoachChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField()),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='accounts.coach')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaching_chat_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sessions Chat History',
                'ordering': ('timestamp',),
            },
        ),
    ]
