# Generated by Django 3.2.13 on 2023-02-23 12:35

import chat.models.chat
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_coachchathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionchathistory',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=chat.models.chat.session_image_directory_path),
        ),
        migrations.AddField(
            model_name='sessionchathistory',
            name='type',
            field=models.CharField(choices=[('text', 'TEXT'), ('file', 'FILE')], default='text', max_length=100, verbose_name='Type of Message'),
        ),
    ]
