# Generated by Django 3.2.1 on 2022-02-01 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email_address', models.EmailField(max_length=255, unique=True, verbose_name='Primary Email Address')),
                ('full_name', models.CharField(max_length=255)),
                ('date_joined', models.DateField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('age', models.CharField(choices=[('range_one', '20-29'), ('range_two', '30-39'), ('range_three', '40-49'), {'Above 50', 'range_four'}], max_length=20, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('undisclosed', 'Prefer not to say'), ('other', 'Other')], max_length=20)),
                ('preferred_language', models.CharField(choices=[('english', 'English'), ('french', 'French'), ('portuguese', 'Portuguese')], max_length=40)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BusinessOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('whatsapp_business_link', models.URLField(blank=True, null=True)),
                ('value_chain', models.CharField(choices=[('chain_one', 'Primary production (farming)'), ('chain_two', 'Input supplier'), ('chain_three', 'Processor (value addition)'), ('chain_four', 'Aggregator'), ('chain_five', 'Distributor'), ('chain_six', 'Retailer'), ('chain_seven', 'Service provider')], max_length=255)),
                ('existence_period', models.CharField(choices=[('period_one', 'Below 1 year'), ('period_two', 'More than 1 year but less than 2 years'), ('period_three', 'Between 2 to 5 years'), ('period_four', 'Over 5 years')], max_length=255)),
                ('stage', models.CharField(choices=[('stage_one', 'Product or service is still being developed'), ('stage_two', 'Product or service is at MVP stage. Currently piloting with target users'), ('stage_three', 'Product or service has been availed in the market. There are no sales or revenues as yet'), ('stage_four', 'Product or service is in the market. There are sales/revenues')], max_length=255)),
                ('organization_owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CovidImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_one', models.TextField()),
                ('impact_two', models.TextField(null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='covid_impact', to='accounts.businessorganization')),
            ],
        ),
    ]
