# Generated by Django 3.2.1 on 2022-01-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_email_address',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Preferred Email Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email_address',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Primary Email Address'),
        ),
    ]
