# Generated by Django 3.2.1 on 2022-02-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_milestone_businesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='businesses',
            field=models.ManyToManyField(blank=True, to='accounts.BusinessOrganization'),
        ),
    ]
