# Generated by Django 3.2.1 on 2022-02-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_milestone_businesses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_address',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='Primary Email Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='milestone',
            name='businesses',
            field=models.ManyToManyField(blank=True, related_name='businesses', to='accounts.BusinessOrganization'),
        ),
    ]
