# Generated by Django 3.2.1 on 2022-01-27 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('facebook_link', models.URLField(null=True)),
                ('twitter_link', models.URLField(null=True)),
                ('instagram_link', models.URLField(null=True)),
                ('linkedin_link', models.URLField(null=True)),
                ('whatsapp_business_link', models.URLField(null=True)),
                ('value_chain', models.CharField(choices=[('chain_one', 'Primary production (farming)'), ('chain_two', 'Input supplier'), ('chain_three', 'Processor (value addition)'), ('chain_four', 'Aggregator'), ('chain_five', 'Distributor'), ('chain_six', 'Retailer'), ('chain_seven', 'Service provider')], max_length=255)),
                ('existence_period', models.CharField(choices=[('period_one', 'Below 1 year'), ('period_two', 'More than 1 year but less than 2 years'), ('period_three', 'Between 2 to 5 years'), ('period_four', 'Over 5 years')], max_length=255)),
                ('stage', models.CharField(choices=[('stage_one', 'Product or service is still being developed'), ('stage_two', 'Product or service is at MVP stage. Currently piloting with target users'), ('stage_three', 'Product or service has been availed in the market. There are no sales or revenues as yet'), ('stage_four', 'Product or service is in the market. There are sales/revenues')], max_length=255)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
