# Generated by Django 3.2.1 on 2022-02-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20220202_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='covidimpact',
            old_name='impact_one',
            new_name='impact',
        ),
        migrations.RemoveField(
            model_name='covidimpact',
            name='impact_two',
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(choices=[('range_one', '20-29'), ('range_two', '30-39'), ('range_three', '40-49'), ('range_four', 'Above 50')], max_length=20, null=True),
        ),
    ]
