# Generated by Django 4.0.2 on 2022-04-30 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_applying_for_a_call_to_action',
            field=models.BooleanField(default=False),
        ),
    ]
