# Generated by Django 3.2.1 on 2022-01-27 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_milestone'),
    ]

    operations = [
        migrations.CreateModel(
            name='CovidImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact_one', models.TextField()),
                ('impact_two', models.TextField(null=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='covid_impact', to='accounts.businessorganization')),
            ],
        ),
    ]
