# Generated by Django 3.2.1 on 2022-02-03 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0001_initial'),
        ('accounts', '0006_alter_businessorganization_organization_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessorganization',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='sme.application'),
        ),
    ]
