# Generated by Django 3.2.1 on 2022-01-27 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_covidimpact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_transcriber',
        ),
    ]
