# Generated by Django 3.2.1 on 2022-02-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_businessorganization_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
