# Generated by Django 4.0.2 on 2022-05-03 12:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentees', to=settings.AUTH_USER_MODEL)),
                ('mentee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coachs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
