# Generated by Django 3.2.1 on 2022-01-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20220127_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(choices=[('range_one', '20-29'), ('range_two', '30-39'), ('range_three', '40-49'), {'range_four', 'Above 50'}], max_length=20, null=True),
        ),
    ]
