# Generated by Django 3.2.1 on 2022-01-31 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='native_language',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_email_address',
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('undisclosed', 'Prefer not to say'), ('other', 'Other')], max_length=20),
        ),
    ]
