# Generated by Django 3.2.1 on 2022-02-01 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20220131_1613'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessorganization',
            old_name='name',
            new_name='organization_name',
        ),
        migrations.RenameField(
            model_name='businessorganization',
            old_name='owner',
            new_name='organization_owner',
        ),
    ]
