# Generated by Django 4.0.2 on 2022-05-03 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_coach_options_alter_coach_mentee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_mentor',
            new_name='is_coach',
        ),
    ]
