# Generated by Django 3.2.1 on 2022-02-01 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20220201_0738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='milestone',
            name='business',
        ),
    ]
