# Generated by Django 4.0.2 on 2022-05-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_is_mentor_user_is_coach'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='coach',
            unique_together={('coach', 'mentee')},
        ),
    ]
