version: '3.7'

services:
  pes:
    build:
      context: .
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      SECRET_KEY: 'secret-key'
      DJANGO_SETTINGS_MODULE: core.settings.development
