# Generated by Django 3.2.1 on 2022-02-23 15:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0004_auto_20220223_1121'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization', to='application.businessorganization')),
                ('subscription_creator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='organization_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
