# Generated by Django 3.2.1 on 2022-02-17 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organization_subscription', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationsubscription',
            name='subscriber',
        ),
        migrations.AddField(
            model_name='organizationsubscription',
            name='organization_subscriber',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organization_subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
