# Generated by Django 3.2.1 on 2022-02-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization_subscription', '0002_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscriber_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
