version: 2.1

orbs:
  cloudrun: circleci/gcp-cloud-run@1.0.2

commands:
  setup_env_file:
    steps:
      - run:
          name: setup_env_file
          command: |
            bash scripts/create_env_file.sh

jobs:
  test_pes:
    machine:
      image: ubuntu-1604:201903-01
    working_directory: ~/PrivateEquity-Support
    steps:
      - checkout
      - setup_env_file
      - run:
          name: Run Tests
          command: |
            make ci-test

workflows:
  version: 2
  rapid:
    jobs:
      - test_pes

