# Generated by Django 3.2.13 on 2022-07-21 06:02

import agripitch.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='An image to display in the call to action page.', upload_to=agripitch.models.competition_image_directory_path)),
                ('tagline', models.CharField(help_text='A title for the call to action.', max_length=255)),
                ('description', models.TextField(help_text='A description of what the call to action is about.')),
                ('slug', models.SlugField(help_text='Unique text to append to the address for the call to action.', max_length=255, unique=True)),
                ('deadline', models.DateTimeField(help_text="The call to action's deadline.")),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date the call to action was created.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The date the call to action was updated.')),
                ('available_for_applications', models.BooleanField(default=False, help_text='Designates whether applications can be made for this call to action. If checked it and is within the deadline, applicants can view it on the application page.')),
            ],
            options={
                'verbose_name_plural': 'Competitions',
            },
        ),
        migrations.CreateModel(
            name='CriteriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='SubCriteriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=400)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_criteria', to='agripitch.criteriaitem')),
            ],
        ),
        migrations.CreateModel(
            name='SubCriteriaRadioFieldInputPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_criteria_radio_inputs', to='agripitch.subcriteriaitem')),
            ],
        ),
        migrations.CreateModel(
            name='SubCriteriaSelectFieldInputPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_criteria_select_inputs', to='agripitch.subcriteriaitem')),
            ],
        ),
        migrations.CreateModel(
            name='SubCriteriaTextFieldInputPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=400)),
                ('sub_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_criteria_text_area_inputs', to='agripitch.subcriteriaitem')),
            ],
        ),
        migrations.CreateModel(
            name='SubCriteriaSelectFieldInputPromptChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=400)),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='agripitch.subcriteriaselectfieldinputprompt')),
            ],
        ),
        migrations.CreateModel(
            name='SubCriteriaRadioFieldInputPromptOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=400)),
                ('sub_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radio_options', to='agripitch.subcriteriaradiofieldinputprompt')),
            ],
        ),
        migrations.CreateModel(
            name='SubCriteriaInputFieldPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=400)),
                ('sub_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_criteria_text_inputs', to='agripitch.subcriteriaitem')),
            ],
        ),
        migrations.CreateModel(
            name='SubCriteriaDocumentPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to=agripitch.models.image_directory_path)),
                ('sub_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_criteria_documents', to='agripitch.subcriteriaitem')),
            ],
        ),
        migrations.CreateModel(
            name='ShortList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlists', to='agripitch.competition', verbose_name='Application')),
            ],
        ),
        migrations.AddField(
            model_name='criteriaitem',
            name='shortlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='agripitch.shortlist'),
        ),
        migrations.CreateModel(
            name='AFDBApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='afdb_application', to=settings.AUTH_USER_MODEL, verbose_name='Applicant')),
            ],
            options={
                'verbose_name_plural': 'AFDB Applications',
            },
        ),
    ]
