# Generated by Django 3.2.13 on 2022-08-06 11:05

import agripitch.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('application', '0006_alter_application_expected_max_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='CriteriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=400)),
            ],
            options={
                'verbose_name_plural': '2. Criteria Items',
            },
        ),
        migrations.CreateModel(
            name='SubCriteriaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=400)),
                ('type', models.CharField(choices=[('charfield', 'CharInput'), ('textfield', 'TextInput'), ('choicefield', 'ChoiceInput'), ('file', 'FileInput'), ('numberfield', 'NumberInput'), ('radiofield', 'RadioInput')], max_length=100)),
                ('position_in_form', models.CharField(default=0, max_length=3)),
                ('description', models.TextField(blank=True, null=True)),
                ('criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_criteria', to='agripitch.criteriaitem')),
            ],
            options={
                'verbose_name_plural': '3. Form Questions',
                'ordering': ('position_in_form',),
            },
        ),
        migrations.CreateModel(
            name='ValidatorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='SubCriteriaTextFieldInputPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(max_length=400)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_area_inputs', to='application.application')),
                ('sub_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_criteria_text_area_inputs', to='agripitch.subcriteriaitem')),
            ],
        ),
        migrations.CreateModel(
            name='SubCriteriaItemFieldProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('class', 'class'), ('accept', 'accept'), ('max_size', 'max_size')], max_length=100)),
                ('value', models.CharField(choices=[('form-input-validate', 'form-input-validate'), ('form-radio', 'form-radio'), ('form-input-validate form-radio', 'form-input-validate form-radio'), ('.pdf', 'PDF'), ('image/*', 'Images')], max_length=400)),
                ('sub_criteria_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='agripitch.subcriteriaitem')),
            ],
        ),
        migrations.CreateModel(
            name='SubCriteriaItemChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('sub_criteria_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='agripitch.subcriteriaitem')),
            ],
        ),
        migrations.CreateModel(
            name='SubCriteriaInputFieldPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=400)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_inputs', to='application.application')),
                ('sub_criteria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_criteria_text_inputs', to='agripitch.subcriteriaitem')),
            ],
        ),
        migrations.CreateModel(
            name='ShortList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlists', to='application.calltoaction', verbose_name='Application')),
            ],
            options={
                'verbose_name_plural': '1. Shortlists',
            },
        ),
        migrations.AddField(
            model_name='criteriaitem',
            name='shortlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='agripitch.shortlist'),
        ),
        migrations.CreateModel(
            name='SubCriteriaItemValidators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=80)),
                ('sub_criteria_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validators', to='agripitch.subcriteriaitem')),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='agripitch.validatortype')),
            ],
            options={
                'unique_together': {('sub_criteria_item', 'validator')},
            },
        ),
        migrations.CreateModel(
            name='SubCriteriaItemResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='application.application')),
                ('sub_criteria_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='agripitch.subcriteriaitem')),
            ],
            options={
                'verbose_name_plural': '4 Responses',
                'unique_together': {('sub_criteria_item', 'application')},
            },
        ),
        migrations.CreateModel(
            name='SubCriteriaItemDocumentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to=agripitch.models.image_directory_path)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_documents', to='application.application')),
                ('sub_criteria_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_criteria_item_documents', to='agripitch.subcriteriaitem')),
            ],
            options={
                'verbose_name_plural': '5 Documents',
                'unique_together': {('sub_criteria_item', 'application')},
            },
        ),
    ]
