# Generated by Django 3.2.13 on 2022-08-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcriteriaitemfieldproperties',
            name='name',
            field=models.CharField(choices=[('class', 'class'), ('accept', 'accept'), ('max_size', 'max_size')], max_length=100),
        ),
        migrations.AlterField(
            model_name='subcriteriaitemfieldproperties',
            name='value',
            field=models.CharField(choices=[('form-input-validate', 'form-input-validate'), ('form-radio', 'form-radio'), ('form-input-validate form-radio', 'form-input-validate form-radio'), ('.pdf', 'PDF'), ('image/*', 'Images')], max_length=400),
        ),
    ]
