# Generated by Django 3.2.13 on 2022-07-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcriteriaitem',
            name='position_in_form',
            field=models.CharField(default=0, max_length=3),
        ),
    ]
