# Generated by Django 3.2.13 on 2022-08-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcriteriaitemfieldproperties',
            name='name',
            field=models.CharField(choices=[('class', 'class'), ('accept', 'accept'), ('max_size', 'max_size'), ('required', 'required')], max_length=100),
        ),
        migrations.AlterField(
            model_name='subcriteriaitemfieldproperties',
            name='value',
            field=models.CharField(choices=[('form-input-validate', 'form-input-validate'), ('form-radio', 'form-radio'), ('form-input-validate form-radio', 'form-input-validate form-radio'), ('.pdf', 'PDF'), ('image/*', 'Images'), ('1048576', '1 MB'), ('2097152', '2 MB'), ('False', 'Not required')], max_length=400),
        ),
    ]
