# Generated by Django 3.2.13 on 2022-08-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcriteriaitem',
            name='type',
            field=models.CharField(choices=[('charfield', 'CharInput'), ('textfield', 'TextInput'), ('choicefield', 'ChoiceInput'), ('file', 'FileInput'), ('numberfield', 'NumberInput'), ('radiofield', 'RadioInput'), ('datefield', 'DateField'), ('countryfield', 'CountryField'), ('datetimefield', 'DateTimeField')], max_length=100),
        ),
    ]
