# Generated by Django 3.2.13 on 2022-07-28 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='SubCriteriaItemFileExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='agripitch.fileextension')),
                ('sub_criteria_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='agripitch.subcriteriaitem')),
            ],
            options={
                'unique_together': {('sub_criteria_item', 'extension')},
            },
        ),
    ]
