# Generated by Django 3.2.13 on 2022-07-21 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcriteriaradiofieldinputpromptoption',
            name='sub_criteria',
        ),
        migrations.RemoveField(
            model_name='subcriteriaselectfieldinputprompt',
            name='sub_criteria',
        ),
        migrations.RemoveField(
            model_name='subcriteriaselectfieldinputpromptchoice',
            name='input',
        ),
        migrations.AddField(
            model_name='subcriteriadocumentprompt',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='agripitch.afdbapplication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcriteriainputfieldprompt',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_inputs', to='agripitch.afdbapplication'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcriteriaitem',
            name='type',
            field=models.CharField(choices=[('charfield', 'Charfield'), ('textfield', 'Textfield'), ('select', 'Select')], max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subcriteriatextfieldinputprompt',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_area_inputs', to='agripitch.afdbapplication'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subcriteriatextfieldinputprompt',
            name='value',
            field=models.TextField(max_length=400),
        ),
        migrations.DeleteModel(
            name='SubCriteriaRadioFieldInputPrompt',
        ),
        migrations.DeleteModel(
            name='SubCriteriaRadioFieldInputPromptOption',
        ),
        migrations.DeleteModel(
            name='SubCriteriaSelectFieldInputPrompt',
        ),
        migrations.DeleteModel(
            name='SubCriteriaSelectFieldInputPromptChoice',
        ),
    ]
