# Generated by Django 3.2.13 on 2022-07-29 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0002_fileextension_subcriteriaitemfileextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='validatortype',
            name='value',
            field=models.CharField(max_length=80),
            preserve_default=False,
        ),
    ]
