# Generated by Django 3.2.13 on 2022-08-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0002_auto_20220807_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcriteriaitem',
            name='type',
            field=models.CharField(choices=[('charfield', 'CharInput'), ('textfield', 'TextInput'), ('choicefield', 'ChoiceInput'), ('file', 'FileInput'), ('numberfield', 'NumberInput'), ('radiofield', 'RadioInput'), ('datefield', 'DateField')], max_length=100),
        ),
        migrations.AlterField(
            model_name='subcriteriaitemresponse',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
