# Generated by Django 3.2.13 on 2022-07-20 17:58

import agripitch.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0002_remove_shortlist_afdb_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='An image to display in the call to action page.', upload_to=agripitch.models.competition_image_directory_path)),
                ('tagline', models.CharField(help_text='A title for the call to action.', max_length=255)),
                ('description', models.TextField(help_text='A description of what the call to action is about.')),
                ('slug', models.SlugField(help_text='Unique text to append to the address for the call to action.', max_length=255, unique=True)),
                ('deadline', models.DateTimeField(help_text="The call to action's deadline.")),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date the call to action was created.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The date the call to action was updated.')),
                ('available_for_applications', models.BooleanField(default=False, help_text='Designates whether applications can be made for this call to action. If checked it and is within the deadline, applicants can view it on the application page.')),
            ],
        ),
    ]
