# Generated by Django 3.2.13 on 2022-07-21 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0002_auto_20220721_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcriteriaitem',
            name='type',
            field=models.CharField(choices=[('charfield', 'Charfield'), ('textfield', 'Textfield'), ('choicefield', 'ChoiceField')], max_length=100),
        ),
        migrations.CreateModel(
            name='SubCriteriaItemResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='agripitch.afdbapplication')),
                ('sub_criteria_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='agripitch.subcriteriaitem')),
            ],
        ),
        migrations.CreateModel(
            name='SubCriteriaItemChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=200)),
                ('sub_criteria_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='agripitch.subcriteriaitem')),
            ],
        ),
    ]
