# Generated by Django 3.2.13 on 2022-07-20 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0003_competition'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='competition',
            options={'verbose_name_plural': 'Competitions'},
        ),
        migrations.AddField(
            model_name='shortlist',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agripitch.competition', verbose_name='Application'),
            preserve_default=False,
        ),
    ]
