# Generated by Django 3.2.13 on 2022-08-12 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0003_alter_subcriteriaitem_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcriteriaitemvalidators',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subcriteriaitemvalidators',
            name='sub_criteria_item',
        ),
        migrations.RemoveField(
            model_name='subcriteriaitemvalidators',
            name='validator',
        ),
        migrations.RemoveField(
            model_name='subcriteriatextfieldinputprompt',
            name='application',
        ),
        migrations.RemoveField(
            model_name='subcriteriatextfieldinputprompt',
            name='sub_criteria',
        ),
        migrations.DeleteModel(
            name='SubCriteriaInputFieldPrompt',
        ),
        migrations.DeleteModel(
            name='SubCriteriaItemValidators',
        ),
        migrations.DeleteModel(
            name='SubCriteriaTextFieldInputPrompt',
        ),
        migrations.DeleteModel(
            name='ValidatorType',
        ),
    ]
