# Generated by Django 3.2.13 on 2022-07-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0003_auto_20220721_1110'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SubCriteriaItemChoices',
            new_name='SubCriteriaItemChoice',
        ),
    ]
