# Generated by Django 3.2.13 on 2022-07-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0003_validatortype_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='validatortype',
            name='value',
        ),
        migrations.AddField(
            model_name='subcriteriaitemvalidators',
            name='value',
            field=models.CharField(max_length=80),
            preserve_default=False,
        ),
    ]
