# Generated by Django 3.2.13 on 2022-08-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_application_expected_max_score'),
        ('agripitch', '0003_alter_subcriteriaitemfieldproperties_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcriteriaitemfieldproperties',
            name='value',
            field=models.CharField(choices=[('form-input-validate', 'form-input-validate'), ('form-radio', 'form-radio'), ('form-input-validate form-radio', 'form-input-validate form-radio'), ('.pdf', 'PDF'), ('image/*', 'Images')], max_length=400),
        ),
        migrations.AlterUniqueTogether(
            name='subcriteriaitemresponse',
            unique_together={('sub_criteria_item', 'application')},
        ),
    ]
