# Generated by Django 3.2.13 on 2022-08-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0004_auto_20220807_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcriteriaitem',
            name='label',
            field=models.CharField(max_length=600),
        ),
    ]
