# Generated by Django 3.2.13 on 2022-07-21 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_application_expected_max_score'),
        ('agripitch', '0004_rename_subcriteriaitemchoices_subcriteriaitemchoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlist',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shortlists', to='application.calltoaction', verbose_name='Application'),
        ),
        migrations.AlterField(
            model_name='subcriteriadocumentprompt',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_documents', to='application.application'),
        ),
        migrations.AlterField(
            model_name='subcriteriainputfieldprompt',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_inputs', to='application.application'),
        ),
        migrations.AlterField(
            model_name='subcriteriaitem',
            name='type',
            field=models.CharField(choices=[('charfield', 'Charfield'), ('textfield', 'Textfield'), ('choicefield', 'ChoiceField'), ('file', 'FileField')], max_length=100),
        ),
        migrations.AlterField(
            model_name='subcriteriaitemresponse',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='application.application'),
        ),
        migrations.AlterField(
            model_name='subcriteriatextfieldinputprompt',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='text_area_inputs', to='application.application'),
        ),
        migrations.DeleteModel(
            name='AFDBApplication',
        ),
        migrations.DeleteModel(
            name='Competition',
        ),
    ]
