# Generated by Django 3.2.13 on 2022-07-20 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0004_auto_20220720_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlist',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competition', to='agripitch.competition', verbose_name='Application'),
        ),
    ]
