# Generated by Django 3.2.13 on 2022-08-12 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0004_auto_20220812_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValidatorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='SubCriteriaItemValidators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=80)),
                ('sub_criteria_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validators', to='agripitch.subcriteriaitem')),
                ('validator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='agripitch.validatortype')),
            ],
            options={
                'unique_together': {('sub_criteria_item', 'validator')},
            },
        ),
    ]
