# Generated by Django 3.2.13 on 2022-08-01 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0004_auto_20220729_1059'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subcriteriaitemfileextension',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subcriteriaitemfileextension',
            name='extension',
        ),
        migrations.RemoveField(
            model_name='subcriteriaitemfileextension',
            name='sub_criteria_item',
        ),
        migrations.DeleteModel(
            name='FileExtension',
        ),
        migrations.DeleteModel(
            name='SubCriteriaItemFileExtension',
        ),
    ]
