# Generated by Django 3.2.13 on 2022-07-20 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0005_alter_shortlist_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlist',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='short_lists', to='agripitch.competition', verbose_name='Application'),
        ),
    ]
