# Generated by Django 3.2.13 on 2022-08-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0005_auto_20220805_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcriteriaitemchoice',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
