# Generated by Django 3.2.13 on 2022-08-02 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0005_auto_20220801_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcriteriaitem',
            name='type',
            field=models.CharField(choices=[('charfield', 'CharInput'), ('textfield', 'TextInput'), ('choicefield', 'ChoiceInput'), ('file', 'FileInput'), ('numberfield', 'NumberInput'), ('radiofield', 'RadioInput')], max_length=100),
        ),
    ]
