# Generated by Django 3.2.13 on 2022-07-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0005_auto_20220721_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcriteriaitem',
            name='position_in_form',
            field=models.CharField(choices=[(1, 'One')], max_length=3),
            preserve_default=False,
        ),
    ]
