# Generated by Django 3.2.13 on 2022-08-03 11:02

import agripitch.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_alter_application_expected_max_score'),
        ('agripitch', '0006_alter_subcriteriaitem_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCriteriaItemDocumentResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('document', models.FileField(upload_to=agripitch.models.image_directory_path)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_documents', to='application.application')),
                ('sub_criteria_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_criteria_item_documents', to='agripitch.subcriteriaitem')),
            ],
        ),
        migrations.DeleteModel(
            name='SubCriteriaDocumentPrompt',
        ),
    ]
