# Generated by Django 3.2.13 on 2022-07-27 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0006_subcriteriaitem_position_in_form'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcriteriaitem',
            options={'ordering': ('position_in_form',)},
        ),
        migrations.AlterField(
            model_name='subcriteriaitem',
            name='position_in_form',
            field=models.CharField(max_length=3),
        ),
    ]
