# Generated by Django 3.2.13 on 2022-08-07 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0006_subcriteriaitemchoice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcriteriaitemfieldproperties',
            name='value',
            field=models.CharField(choices=[('form-input-validate', 'form-input-validate'), ('form-radio', 'form-radio'), ('form-input-validate form-radio', 'form-input-validate form-radio'), ('.pdf', 'PDF'), ('image/*', 'Images'), (1048576, '1 MB'), (2097152, '2 MB')], max_length=400),
        ),
    ]
