# Generated by Django 3.2.13 on 2022-08-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0007_auto_20220803_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcriteriaitemfieldproperties',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='subcriteriaitemfieldproperties',
            name='value',
            field=models.CharField(max_length=400),
        ),
    ]
