# Generated by Django 3.2.13 on 2022-07-21 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0007_alter_shortlist_competition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcriteriaitem',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_criteria', to='agripitch.criteriaitem'),
        ),
    ]
