# Generated by Django 3.2.13 on 2022-07-27 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0007_auto_20220727_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCriteriaItemFieldProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('value', models.CharField(max_length=40)),
                ('sub_criteria_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='agripitch.subcriteriaitem')),
            ],
        ),
    ]
