# Generated by Django 3.2.13 on 2022-08-22 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0008_partnerlogo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerlogo',
            options={'ordering': ('position',)},
        ),
    ]
