# Generated by Django 3.2.13 on 2022-08-22 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0009_alter_partnerlogo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerlogo',
            options={'ordering': ('position',), 'verbose_name_plural': '6 Partner Logos'},
        ),
        migrations.AlterField(
            model_name='partnerlogo',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
