# Generated by Django 3.2.13 on 2022-08-22 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0010_auto_20220822_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnerlogo',
            name='title',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
