# Generated by Django 3.2.13 on 2022-08-22 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0011_alter_partnerlogo_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partnerlogo',
            old_name='link',
            new_name='website',
        ),
    ]
