# Generated by Django 3.2.13 on 2022-09-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0013_alter_subcriteriaitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcriteriaitem',
            name='type',
            field=models.CharField(choices=[('charfield', 'One Line Text'), ('textfield', 'Multiple Line Text'), ('choicefield', 'Dropdown'), ('file', 'File'), ('numberfield', 'Number'), ('radiofield', 'Choice'), ('datefield', 'Date'), ('countryfield', 'Country'), ('multiplechoicefield', 'Multiple Choice Field')], max_length=100),
        ),
    ]
