# Generated by Django 3.2.13 on 2022-09-12 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0014_alter_subcriteriaitem_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcriteriaitemfieldproperties',
            name='value',
            field=models.CharField(choices=[('form-input-validate', 'form-input-validate'), ('form-radio', 'form-radio'), ('form-input-validate form-radio', 'form-input-validate form-radio'), ('.pdf', 'PDF'), ('image/*', 'Images'), ('1048576', '1 MB'), ('2097152', '2 MB'), ('False', 'Not required'), ('1987-01-01', 'Min Year'), ('2004-01-01', 'Max Year'), ('multiple_checkbox', 'Multiple Checkbox')], max_length=400),
        ),
    ]
