# Generated by Django 3.2.13 on 2022-09-13 02:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0018_auto_20220913_0148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcriteriaitem',
            name='list_value',
        ),
        migrations.AddField(
            model_name='subcriteriaitemresponse',
            name='list_value',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=10, null=True), size=8), blank=True, null=True, size=8),
        ),
    ]
