# Generated by Django 3.2.13 on 2022-09-13 02:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0020_alter_subcriteriaitemresponse_list_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcriteriaitemresponse',
            name='list_value',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=400, null=True), size=None), blank=True, null=True, size=None),
        ),
    ]
