# Generated by Django 3.2.13 on 2022-09-13 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0021_alter_subcriteriaitemresponse_list_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partnerlogo',
            options={'ordering': ['position'], 'verbose_name_plural': '6 Partner Logos'},
        ),
        migrations.AlterModelOptions(
            name='subcriteriaitem',
            options={'ordering': ['position_in_form'], 'verbose_name_plural': '3. Form Questions'},
        ),
    ]
