# Generated by Django 3.2.13 on 2022-09-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0023_auto_20220915_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcriteriaitem',
            name='position_in_form',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
