# Generated by Django 3.2.13 on 2022-09-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0025_alter_subcriteriaitem_position_in_form'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcriteriaitem',
            name='position_in_form',
            field=models.IntegerField(default=1),
        ),
    ]
