# Generated by Django 3.2.13 on 2022-09-16 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0026_alter_subcriteriaitem_position_in_form'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcriteriaitemchoice',
            name='description',
        ),
    ]
