# Generated by Django 3.2.13 on 2022-09-25 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0027_remove_subcriteriaitemchoice_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcriteriaitemresponse',
            name='value',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
