# Generated by Django 3.2.13 on 2022-09-25 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0028_alter_subcriteriaitemresponse_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcriteriaitemresponse',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
