# Generated by Django 3.2.13 on 2022-10-14 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0028_subcriteriaitem_description_fr'),
        ('agripitch', '0029_alter_subcriteriaitemresponse_value'),
    ]

    operations = [
    ]
