# Generated by Django 3.2.13 on 2022-10-15 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0030_merge_20221014_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcriteriaitemchoice',
            options={'verbose_name_plural': '7 Choices'},
        ),
    ]
