# Generated by Django 3.2.13 on 2022-10-16 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0031_alter_subcriteriaitemchoice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='criteriaitem',
            options={'ordering': ['position_in_form'], 'verbose_name_plural': '2. Criteria Items'},
        ),
        migrations.AddField(
            model_name='criteriaitem',
            name='position_in_form',
            field=models.IntegerField(default=1),
        ),
    ]
