# Generated by Django 3.2.13 on 2022-11-05 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0032_auto_20221016_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=500)),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scales', to='agripitch.subcriteriaitem')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=500)),
                ('score', models.IntegerField()),
                ('scale', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='agripitch.scale')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
