# Generated by Django 3.2.13 on 2022-11-05 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0033_scale_scaleitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scale',
            options={'verbose_name_plural': '8. Scales'},
        ),
        migrations.AlterModelOptions(
            name='scaleitem',
            options={'verbose_name_plural': '9. Scale Items'},
        ),
    ]
