# Generated by Django 3.2.13 on 2022-11-05 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0034_auto_20221105_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scale',
            name='question',
        ),
    ]
