# Generated by Django 3.2.13 on 2022-11-07 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_alter_application_options'),
        ('agripitch', '0039_alter_scaleitem_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoring',
            name='score',
        ),
        migrations.CreateModel(
            name='ApplicationMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='application.application')),
                ('scoring', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scoring', to='agripitch.scoring')),
            ],
            options={
                'verbose_name_plural': '11. Applications Marks',
            },
        ),
    ]
