# Generated by Django 3.2.13 on 2022-11-07 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0013_alter_application_options'),
        ('agripitch', '0041_auto_20221107_2107'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationmarks',
            unique_together={('application', 'scoring')},
        ),
    ]
