# Generated by Django 3.2.13 on 2022-11-08 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0043_alter_applicationmarks_scoring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmarks',
            name='scoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_scores', to='agripitch.scoring'),
        ),
    ]
