# Generated by Django 3.2.13 on 2022-11-10 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0045_remove_scaleitem_scale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoringItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scales', to='agripitch.scaleitem')),
                ('scale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='agripitch.scale')),
            ],
        ),
    ]
