# Generated by Django 3.2.13 on 2022-11-10 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0046_scoringitems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scoringitems',
            options={'verbose_name_plural': '12. Scoring'},
        ),
    ]
