# Generated by Django 3.2.13 on 2022-11-14 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_alter_applicationreview_reviewer'),
        ('agripitch', '0049_alter_scoringitems_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmarks',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='agripitch.subcriteriaitem'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='applicationmarks',
            unique_together={('application', 'question')},
        ),
        migrations.RemoveField(
            model_name='applicationmarks',
            name='scoring',
        ),
    ]
