# Generated by Django 3.2.13 on 2022-11-15 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0050_auto_20221114_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmarks',
            name='scoring',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='agripitch.scoring'),
            preserve_default=False,
        ),
    ]
