# Generated by Django 3.2.13 on 2022-12-03 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agripitch', '0052_alter_applicationmarks_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmarks',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marks', to=settings.AUTH_USER_MODEL),
        ),
    ]
