# Generated by Django 3.2.13 on 2022-12-05 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0021_questioncomment'),
        ('agripitch', '0054_alter_applicationmarks_reviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhaseTwoApplicationMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_marks', models.IntegerField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phase_two_marks', to='application.application')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phase_two_marks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
