# Generated by Django 3.2.13 on 2022-12-05 12:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_questioncomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('agripitch', '0055_phasetwoapplicationmarks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phasetwoapplicationmarks',
            options={'verbose_name_plural': '12. Applications Marks'},
        ),
        migrations.AlterUniqueTogether(
            name='phasetwoapplicationmarks',
            unique_together={('application', 'reviewer')},
        ),
    ]
