# Generated by Django 3.2.13 on 2022-12-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0056_auto_20221205_1526'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phasetwoapplicationmarks',
            options={'verbose_name_plural': '12. Phase 2 Applications Marks'},
        ),
    ]
