# Generated by Django 3.2.1 on 2022-02-01 09:51

from django.db import migrations, models
import sme.models.application


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='An image to display in the applications page.', upload_to=sme.models.application.image_directory_path)),
                ('tagline', models.CharField(help_text='A title for the application.', max_length=255)),
                ('description', models.TextField(help_text='A description of what the application is about.')),
                ('slug', models.SlugField(help_text='Unique text to append to the address for the application.', max_length=255, unique=True)),
                ('deadline', models.DateTimeField(help_text="The application's deadline.")),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date the application was created.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The date the application was updated.')),
                ('available_for_applications', models.BooleanField(default=False, help_text='Designates whether applications can be made for this application. If checked it and is within the deadline, applicants can view it on the application page.')),
            ],
        ),
    ]
