# Generated by Django 3.2.1 on 2022-01-19 11:32

from django.db import migrations, models
import django.utils.timezone
import sme.models.application


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='available_for_applications',
            field=models.BooleanField(default=True, help_text='Designates whether applications can be made for this application. If checked it and is within the deadline, applicants can view it on the application page.'),
        ),
        migrations.AddField(
            model_name='application',
            name='created',
            field=models.DateTimeField(auto_now_add=True, help_text='The date the application was created.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='deadline',
            field=models.DateTimeField(help_text="The application's deadline."),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='The date the application was updated.'),
        ),
        migrations.AlterField(
            model_name='application',
            name='image',
            field=models.ImageField(help_text='An image to display in the applications page.', upload_to=sme.models.application.image_directory_path),
        ),
        migrations.AlterField(
            model_name='application',
            name='slug',
            field=models.SlugField(help_text='Unique text to append to the address for the application.', max_length=255, unique=True),
        ),
    ]
