# Generated by Django 3.2.1 on 2022-01-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sme', '0002_auto_20220119_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='available_for_applications',
            field=models.BooleanField(default=False, help_text='Designates whether applications can be made for this application. If checked it and is within the deadline, applicants can view it on the application page.'),
        ),
    ]
