# Generated by Django 3.2.13 on 2022-11-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortListGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.CharField(choices=[('step_one', 'Application Data Not Submitted')], default='step_one', max_length=100, verbose_name='Group')),
            ],
            options={
                'verbose_name_plural': '1. Short List Group',
            },
        ),
    ]
