# Generated by Django 3.2.13 on 2022-11-14 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0050_auto_20221114_2002'),
        ('eligibility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortListGroupItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='eligibility.shortlistgroup')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='agripitch.subcriteriaitem')),
            ],
            options={
                'verbose_name_plural': '2. Short List Group Items',
            },
        ),
    ]
