# Generated by Django 3.2.13 on 2022-11-14 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0002_shortlistgroupitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shortlistgroup',
            name='group',
            field=models.CharField(choices=[('step_one', 'Eligibility Verification'), ('step_two', 'Document Verification'), ('step_three', 'Long List'), ('step_four', 'Short List')], default='step_one', max_length=100, verbose_name='Group'),
        ),
    ]
