# Generated by Django 3.2.13 on 2022-11-14 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0003_alter_shortlistgroup_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistgroup',
            name='slug',
            field=models.SlugField(help_text='Unique text to append to the address for the application.', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
