# Generated by Django 3.2.13 on 2022-11-16 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_application_disqualified'),
        ('eligibility', '0004_shortlistgroup_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus', models.IntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonus', to='application.application')),
            ],
        ),
    ]
