# Generated by Django 3.2.13 on 2022-11-16 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0005_bonuspoints'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bonuspoints',
            options={'verbose_name_plural': '2. Bonus'},
        ),
        migrations.AlterModelOptions(
            name='shortlistgroupitems',
            options={'verbose_name_plural': '1. Short List Group Items'},
        ),
        migrations.AddField(
            model_name='bonuspoints',
            name='step',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus', to='eligibility.shortlistgroup'),
        ),
    ]
