# Generated by Django 3.2.13 on 2022-11-16 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0006_auto_20221116_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='shortlistgroup',
            name='bonus_to_award',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='shortlistgroup',
            name='has_bonus',
            field=models.BooleanField(default=False),
        ),
    ]
