# Generated by Django 3.2.13 on 2022-11-18 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eligibility', '0007_auto_20221116_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bonuspoints',
            name='step',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus', to='eligibility.shortlistgroup'),
        ),
    ]
