# Generated by Django 3.2.1 on 2022-02-23 09:03

import application.models.call_to_action
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(max_length=255)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('whatsapp_business_link', models.URLField(blank=True, null=True)),
                ('value_chain', models.CharField(choices=[('chain_one', 'Primary production (farming)'), ('chain_two', 'Input supplier'), ('chain_three', 'Processor (value addition)'), ('chain_four', 'Aggregator'), ('chain_five', 'Distributor'), ('chain_six', 'Retailer'), ('chain_seven', 'Service provider')], max_length=255)),
                ('existence_period', models.CharField(choices=[('period_one', 'Below 1 year'), ('period_two', 'More than 1 year but less than 2 years'), ('period_three', 'Between 2 to 5 years'), ('period_four', 'Over 5 years')], max_length=255)),
                ('stage', models.CharField(choices=[('stage_one', 'Product or service is still being developed'), ('stage_two', 'Product or service is at MVP stage. Currently piloting with target users'), ('stage_three', 'Product or service has been availed in the market. There are no sales or revenues as yet'), ('stage_four', 'Product or service is in the market. There are sales/revenues')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='An image to display in the call to action page.', upload_to=application.models.call_to_action.image_directory_path)),
                ('tagline', models.CharField(help_text='A title for the call to action.', max_length=255)),
                ('description', models.TextField(help_text='A description of what the call to action is about.')),
                ('slug', models.SlugField(help_text='Unique text to append to the address for the call to action.', max_length=255, unique=True)),
                ('deadline', models.DateTimeField(help_text="The call to action's deadline.")),
                ('created', models.DateTimeField(auto_now_add=True, help_text='The date the call to action was created.')),
                ('updated', models.DateTimeField(auto_now=True, help_text='The date the call to action was updated.')),
                ('available_for_applications', models.BooleanField(default=False, help_text='Designates whether applications can be made for this call to action. If checked it and is within the deadline, applicants can view it on the application page.')),
                ('status', models.CharField(choices=[('step_one', 'Application Data Not Submitted'), ('step_two', 'Documents in review'), ('step_three', 'Approved')], default='step_one', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(max_length=255)),
                ('businesses', models.ManyToManyField(blank=True, related_name='businesses', to='application.BusinessOrganization')),
            ],
        ),
        migrations.CreateModel(
            name='CovidImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact', models.TextField()),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='covid_impact', to='application.businessorganization')),
            ],
        ),
        migrations.AddField(
            model_name='businessorganization',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='application.calltoaction'),
        ),
        migrations.AddField(
            model_name='businessorganization',
            name='organization_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to=settings.AUTH_USER_MODEL),
        ),
    ]
