# Generated by Django 4.0.2 on 2022-06-05 13:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationreview',
            unique_together={('application', 'reviewer')},
        ),
    ]
