# Generated by Django 3.2.13 on 2022-08-12 12:03

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calltoaction',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='A description of what the call to action is about.'),
        ),
    ]
