# Generated by Django 3.2.1 on 2022-02-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calltoaction',
            name='status',
        ),
        migrations.AddField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('step_one', 'Application Data Not Submitted'), ('step_two', 'Documents in review'), ('step_three', 'Approved')], default='step_one', max_length=100),
        ),
    ]
