# Generated by Django 3.2.13 on 2022-08-12 12:45

import application.models.carousel_images
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_calltoaction_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=200)),
                ('image', models.FileField(upload_to=application.models.carousel_images.image_directory_path)),
            ],
        ),
    ]
