# Generated by Django 4.0.2 on 2022-06-13 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_applicationreview_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDraftData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook_link', models.URLField(blank=True, null=True)),
                ('twitter_link', models.URLField(blank=True, null=True)),
                ('instagram_link', models.URLField(blank=True, null=True)),
                ('linkedin_link', models.URLField(blank=True, null=True)),
                ('whatsapp_business_link', models.URLField(blank=True, null=True)),
                ('value_chain', models.CharField(blank=True, max_length=100, null=True)),
                ('existence_period', models.CharField(blank=True, max_length=100, null=True)),
                ('stage', models.CharField(blank=True, max_length=100, null=True)),
                ('milestones', models.TextField(blank=True, null=True)),
                ('covid_19_impact', models.TextField(blank=True, null=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='application.application')),
            ],
        ),
    ]
