# Generated by Django 4.0.2 on 2022-06-14 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_applicationdraftdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationdraftdata',
            old_name='covid_19_impact',
            new_name='impact',
        ),
    ]
