# Generated by Django 3.2.1 on 2022-02-23 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_auto_20220223_1001'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='calltoaction',
            options={'verbose_name_plural': 'Calls to Action'},
        ),
        migrations.RemoveField(
            model_name='businessorganization',
            name='application',
        ),
    ]
