# Generated by Django 3.2.13 on 2022-08-31 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('agripitch', '0013_alter_subcriteriaitem_type'),
        ('application', '0003_carouselimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationprompt',
            name='question_position',
        ),
        migrations.AddField(
            model_name='applicationprompt',
            name='prompt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='agripitch.subcriteriaitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationprompt',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application'),
        ),
    ]
