# Generated by Django 4.0.2 on 2022-06-14 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_rename_covid_19_impact_applicationdraftdata_impact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationdraftdata',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='draft', to='application.application'),
        ),
    ]
