# Generated by Django 3.2.1 on 2022-02-28 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_auto_20220223_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='slug',
            field=models.SlugField(help_text='Unique text to append to the address for the application.', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
