# Generated by Django 3.2.13 on 2022-09-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20220831_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
