# Generated by Django 3.2.13 on 2022-06-28 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_alter_applicationdraftdata_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='expected_max_score',
            field=models.IntegerField(default=35, verbose_name='Expected Max Score'),
        ),
    ]
