# Generated by Django 4.0.3 on 2022-03-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_applicationdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_in_review',
            field=models.BooleanField(default=False),
        ),
    ]
