# Generated by Django 3.2.13 on 2022-10-05 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_alter_carouselimage_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='country',
        ),
        migrations.RemoveField(
            model_name='application',
            name='expected_max_score',
        ),
        migrations.RemoveField(
            model_name='application',
            name='milestones',
        ),
    ]
