# Generated by Django 3.2.13 on 2022-10-11 17:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_auto_20221005_0730'),
    ]

    operations = [
        migrations.AddField(
            model_name='carouselimage',
            name='caption_fr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
