# Generated by Django 4.0.3 on 2022-03-14 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_application_eligibility'),
        ('application', '0009_alter_applicationreview_application_and_more'),
    ]

    operations = [
    ]
