# Generated by Django 3.2.13 on 2022-10-11 18:05

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_carouselimage_caption_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='calltoaction',
            name='description_fr',
            field=ckeditor.fields.RichTextField(blank=True, help_text='A description of what the call to action is about.', null=True),
        ),
    ]
