# Generated by Django 3.2.13 on 2022-10-15 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_calltoaction_description_fr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationDraftData',
        ),
    ]
