# Generated by Django 4.0.3 on 2022-03-15 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_merge_20220314_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('step_one', 'Application Data Not Submitted'), ('step_two', 'Data Submitted'), ('step_two', 'Documents in review'), ('step_three', 'verdict Passed')], default='step_one', max_length=100),
        ),
    ]
