# Generated by Django 3.2.13 on 2022-10-26 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_delete_applicationdraftdata'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['created'], 'verbose_name_plural': '1. User Applications'},
        ),
    ]
