# Generated by Django 4.0.3 on 2022-03-15 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_application_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='status',
            new_name='stage',
        ),
    ]
