# Generated by Django 4.0.3 on 2022-03-15 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_rename_status_application_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='to_advance',
            field=models.BooleanField(default=False, help_text='Whether to advance or avoid the application'),
        ),
    ]
