# Generated by Django 3.2.13 on 2022-11-14 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_alter_applicationreview_reviewer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('step_one', 'Application Data Not Submitted'), ('step_two', 'Data Submitted'), ('step_three', 'Eligibility Verification'), ('step_four', 'Document Verification'), ('step_five', 'Long List'), ('step_six', 'Short List'), ('step_seven', 'Verdict Passed')], default='step_one', max_length=100, verbose_name='Stage'),
        ),
    ]
