# Generated by Django 3.2.13 on 2022-11-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_alter_application_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='disqualified',
            field=models.BooleanField(default=False, help_text='Whether application is disqualified', verbose_name='Whether disqualified'),
        ),
    ]
