# Generated by Django 3.2.13 on 2022-11-16 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_application_disqualified'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationreview',
            unique_together=set(),
        ),
    ]
