# Generated by Django 4.0.3 on 2022-03-18 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0017_applicationscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='milestones',
            field=models.TextField(),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationprompt',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='application.application'),
        ),
        migrations.AlterField(
            model_name='applicationprompt',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prompts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='applicationscore',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='application.application'),
        ),
        migrations.AlterField(
            model_name='applicationscore',
            name='reviewer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scores', to=settings.AUTH_USER_MODEL),
        ),
    ]
