# Generated by Django 3.2.13 on 2022-11-17 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_alter_applicationreview_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['id']},
        ),
    ]
