# Generated by Django 3.2.13 on 2022-11-17 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0018_alter_application_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'ordering': ['application_creator__id']},
        ),
        migrations.AlterModelOptions(
            name='applicationdocument',
            options={'ordering': ['application__application_creator_id']},
        ),
    ]
