# Generated by Django 4.0.3 on 2022-03-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0019_applicationcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationscore',
            name='question_position',
            field=models.IntegerField(help_text='The position of the question in the form'),
            preserve_default=False,
        ),
    ]
