# Generated by Django 4.0.3 on 2022-03-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0020_applicationscore_question_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationscore',
            name='question_position',
            field=models.CharField(help_text='The position of the question in the form', max_length=5),
        ),
    ]
