# Generated by Django 3.2.13 on 2022-12-16 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0021_questioncomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationreview',
            options={'ordering': ['application']},
        ),
    ]
