# Generated by Django 4.0.3 on 2022-03-18 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0022_alter_applicationscore_question_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationprompt',
            name='question_position',
            field=models.IntegerField(help_text='The position of the question in the form'),
            preserve_default=False,
        ),
    ]
