# Generated by Django 4.0.3 on 2022-03-21 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0023_applicationprompt_question_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='expected_max_score',
            field=models.IntegerField(default=0),
        ),
    ]
