# Generated by Django 4.0.3 on 2022-03-22 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0024_application_expected_max_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('step_one', 'Application Data Not Submitted'), ('step_two', 'Data Submitted'), ('step_three', 'Documents in review'), ('step_four', 'Verdict Passed')], default='step_one', max_length=100),
        ),
    ]
