# Generated by Django 3.2.1 on 2022-03-31 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('application', '0025_alter_application_stage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name_plural': 'User Applications'},
        ),
        migrations.AlterField(
            model_name='application',
            name='application_creator',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to=settings.AUTH_USER_MODEL, verbose_name='Application Creator'),
        ),
        migrations.AlterField(
            model_name='application',
            name='call_to_action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='application.calltoaction', verbose_name='Call To Action'),
        ),
        migrations.AlterField(
            model_name='application',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date Created'),
        ),
        migrations.AlterField(
            model_name='application',
            name='eligibility',
            field=models.BooleanField(default=False, verbose_name='Eligibility'),
        ),
        migrations.AlterField(
            model_name='application',
            name='expected_max_score',
            field=models.IntegerField(default=0, verbose_name='Expected Max Score'),
        ),
        migrations.AlterField(
            model_name='application',
            name='is_in_review',
            field=models.BooleanField(default=False, verbose_name='In Review'),
        ),
        migrations.AlterField(
            model_name='application',
            name='milestones',
            field=models.TextField(verbose_name='Milestones'),
        ),
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('step_one', 'Application Data Not Submitted'), ('step_two', 'Data Submitted'), ('step_three', 'Documents in review'), ('step_four', 'Verdict Passed')], default='step_one', max_length=100, verbose_name='Stage'),
        ),
        migrations.AlterField(
            model_name='application',
            name='to_advance',
            field=models.BooleanField(default=False, help_text='Whether to advance or avoid the application', verbose_name='Whether to Advance'),
        ),
        migrations.AlterField(
            model_name='application',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Updated'),
        ),
        migrations.AlterField(
            model_name='applicationscore',
            name='score',
            field=models.IntegerField(choices=[(1, 'Strongly Disagree'), (2, 'Disagree'), (3, 'Neutral'), (4, 'Agree'), (5, 'Strongly Agree')], default=1),
        ),
    ]
