# Generated by Django 4.0.2 on 2022-05-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='title',
            field=models.CharField(max_length=400),
            preserve_default=False,
        ),
    ]
