# Generated by Django 4.0.2 on 2022-05-15 07:28

from django.db import migrations, models
import django.db.models.deletion
import staff.models.material


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_session_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=200)),
                ('material', models.FileField(upload_to=staff.models.material.image_directory_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='staff.session')),
            ],
        ),
    ]
