# Generated by Django 4.0.2 on 2022-05-15 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_sessionmaterial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='session',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
    ]
