# Generated by Django 4.0.2 on 2022-05-14 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_meeting'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='url',
            new_name='link',
        ),
    ]
